title: Nauka Jazdy Zygzag Bielsko-Biała
email:
description: >- # this means to ignore newlines until "baseurl:"
  Witamy w Ośrodku Szkolenia Kierowców "Zygzak" w Bielsku - Białej. Zapraszamy Państwa na kurs Prawo Jazdy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
